### Arithmatic operations on NumPy array

#### Addition

In [1]:
import numpy as np

In [2]:
x = np.array([[7, 8, -1],[0, -1, 1]])

x.shape

(2, 3)

In [4]:
x

array([[ 7,  8, -1],
       [ 0, -1,  1]])

In [5]:
x + 2    # broadcasting (add value 2 to all the elements of the array)

array([[ 9, 10,  1],
       [ 2,  1,  3]])

In [6]:
y = np.array([[3, 4, 5], [9, 7, 2]])

y

array([[3, 4, 5],
       [9, 7, 2]])

In [8]:
x + y   # Element wise addition

array([[10, 12,  4],
       [ 9,  6,  3]])

In [9]:
z = np.array([[2, 4, 5]])

z

array([[2, 4, 5]])

In [10]:
y + z   # broadcasting 

array([[ 5,  8, 10],
       [11, 11,  7]])

In [11]:
w = np.array([[2, 5]]).T  # .T is transpose

w

array([[2],
       [5]])

In [17]:
y + np.array([[2, 5]])

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [16]:
np.array([[2, 5]]).shape

(1, 2)

In [12]:
w.shape

(2, 1)

In [13]:
x

array([[ 7,  8, -1],
       [ 0, -1,  1]])

In [14]:
x + w  # broadcasting

array([[ 9, 10,  1],
       [ 5,  4,  6]])

#### Subtraction

In [18]:
x - 3.5

array([[ 3.5,  4.5, -4.5],
       [-3.5, -4.5, -2.5]])

#### Multiplication and division

In [19]:
x

array([[ 7,  8, -1],
       [ 0, -1,  1]])

In [20]:
x * 3  # broadcasting

array([[21, 24, -3],
       [ 0, -3,  3]])

In [21]:
y

array([[3, 4, 5],
       [9, 7, 2]])

In [22]:
x * y   # element wise product -> Hadamard product

array([[21, 32, -5],
       [ 0, -7,  2]])

In [23]:
x / 3

array([[ 2.33333333,  2.66666667, -0.33333333],
       [ 0.        , -0.33333333,  0.33333333]])

In [24]:
x / y

array([[ 2.33333333,  2.        , -0.2       ],
       [ 0.        , -0.14285714,  0.5       ]])

### Vectorized function

In [25]:
def return_max_value(x, y):
    if x > y:
        return x
    else:
        return y

In [26]:
return_max_value(3, 6)

6

In [27]:
array1 = np.array([2, 3, 4, 1])
array2 = np.array([3, 4, 2, 6])

In [28]:
return_max_value(array1, array2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
return_max_value_vect = np.vectorize(return_max_value)  # vectorizing the function

In [30]:
return_max_value_vect

In [31]:
return_max_value_vect(array1, array2)

array([3, 4, 4, 6])

In [ ]:
# np.array(return_max_value(2,3), return_max_value(3,4), ....])

In [32]:
from math import factorial

In [33]:
factorial(6)

720

In [34]:
factorial(array1)

TypeError: only integer scalar arrays can be converted to a scalar index

In [35]:
np.vectorize(factorial)(array1)

array([ 2,  6, 24,  1])

In [36]:
array1

array([2, 3, 4, 1])

In [38]:
from math import sin, cos, log, exp

In [39]:
sin(3)

0.1411200080598672

In [40]:
cos(3)

-0.9899924966004454

In [41]:
log(5)

1.6094379124341003

In [42]:
exp(2)

7.38905609893065

In [43]:
np.sin(array1)

array([ 0.90929743,  0.14112001, -0.7568025 ,  0.84147098])

In [44]:
np.sin(3)

np.float64(0.1411200080598672)

In [45]:
np.log(array2)

array([1.09861229, 1.38629436, 0.69314718, 1.79175947])

In [46]:
from math import pi

In [47]:
np.sin(pi)

np.float64(1.2246467991473532e-16)

In [48]:
np.cos(pi)

np.float64(-1.0)

## Pandas

pandas -> Panel Data 

Panel Data is like spreadsheet. In relational database also you have this spreadsheet like format where each columns are fields, and each rows are called entries. 

[Pandas Documentation](https://pandas.pydata.org/docs/)

### Advantages of pandas

1. Fast execution
2. Enriched I/O: It has APIs to read from various sources (csv, xlsx, rdbms, html, etc.) and it can also write in those formats.
3. Open source community

In [2]:
import pandas as pd

### Pandas Series

In [6]:
s = pd.Series(data=[1, 2, 3.2, 4, 5], index=None)

In [7]:
s

0    1.0
1    2.0
2    3.2
3    4.0
4    5.0
dtype: float64

In [5]:
type(s)

pandas.core.series.Series

In [8]:
s = pd.Series(data=[1, 2, 3.2, 4, 5], index=['a','b','c','d','e'])

s

a    1.0
b    2.0
c    3.2
d    4.0
e    5.0
dtype: float64

In [9]:
independence = {"India": 1947, "Bangladesh": 1971, "China": 1945}

pd.Series(independence)

India         1947
Bangladesh    1971
China         1945
dtype: int64

### Pandas DataFrame
```python
df = pd.DataFrame(data, index=None, columns=None)
````

In [10]:
arr = np.array([[3,0],[2,3],[0,7],[1,2]])

arr

array([[3, 0],
       [2, 3],
       [0, 7],
       [1, 2]])

In [11]:
arr.shape

(4, 2)

In [12]:
pd.DataFrame(arr)

0  1
0  3  0
1  2  3
2  0  7
3  1  2

In [13]:
pd.DataFrame(arr, index=['a','b','c','d'], columns=['xyz', 'pqr'])

xyz  pqr
a    3    0
b    2    3
c    0    7
d    1    2

In [14]:
df = pd.DataFrame(arr, columns=['apple', 'orange'])

df

apple  orange
0      3       0
1      2       3
2      0       7
3      1       2

In [15]:
type(df)

pandas.core.frame.DataFrame

In [19]:
dict1 = {"apples": [3, 2, 0, 1], "oranges": [0, 3, '7', 2]}

pd.DataFrame(dict1)

apples oranges
0       3       0
1       2       3
2       0       7
3       1       2

In [20]:
pd.DataFrame(dict1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   apples   4 non-null      int64 
 1   oranges  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes


In [18]:
pd.DataFrame(dict1, columns=["apples"])

apples
0       3
1       2
2       0
3       1

In [21]:
covid_data = pd.read_csv("./worldometer_coronavirus_summary_data.csv")

In [22]:
covid_data

country          continent  total_confirmed  \
0                  Afghanistan               Asia           179267   
1                      Albania             Europe           275574   
2                      Algeria             Africa           265816   
3                      Andorra             Europe            42156   
4                       Angola             Africa            99194   
..                         ...                ...              ...   
221  Wallis And Futuna Islands  Australia/Oceania              454   
222             Western Sahara             Africa               10   
223                      Yemen               Asia            11819   
224                     Zambia             Africa           320591   
225                   Zimbabwe             Africa           249206   

     total_deaths  total_recovered  active_cases  serious_or_critical  \
0          7690.0         162202.0        9375.0               1124.0   
1          3497.0         271826.0         251.0                  2.0   
2          6875.0         178371.0       80570.0                  6.0   
3           153.0          41021.0         982.0                 14.0   
4          1900.0          97149.0         145.0                  NaN   
..            ...              ...           ...                  ...   
221           7.0            438.0           9.0                  NaN   
222           1.0              9.0           0.0                  NaN   
223        2149.0           9009.0         661.0                 23.0   
224        3983.0         315997.0         611.0                  NaN   
225        5482.0         242417.0        1307.0                 12.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
0                             4420                           190.0   
1                            95954                          1218.0   
2                             5865                           152.0   
3                           543983                          1974.0   
4                             2853                            55.0   
..                             ...                             ...   
221                          41755                           644.0   
222                             16                             2.0   
223                            381                            69.0   
224                          16575                           206.0   
225                          16324                           359.0   

     total_tests  total_tests_per_1m_population  population  
0       951337.0                        23455.0    40560636  
1      1817530.0                       632857.0     2871945  
2       230861.0                         5093.0    45325517  
3       249838.0                      3223924.0       77495  
4      1499795.0                        43136.0    34769277  
..           ...                            ...         ...  
221      20508.0                      1886140.0       10873  
222          NaN                            NaN      624681  
223     265253.0                         8543.0    31049015  
224    3452554.0                       178497.0    19342381  
225    2287793.0                       149863.0    15265849  

[226 rows x 12 columns]

In [25]:
covid_data.head()

country continent  total_confirmed  total_deaths  total_recovered  \
0  Afghanistan      Asia           179267        7690.0         162202.0   
1      Albania    Europe           275574        3497.0         271826.0   
2      Algeria    Africa           265816        6875.0         178371.0   
3      Andorra    Europe            42156         153.0          41021.0   
4       Angola    Africa            99194        1900.0          97149.0   

   active_cases  serious_or_critical  total_cases_per_1m_population  \
0        9375.0               1124.0                           4420   
1         251.0                  2.0                          95954   
2       80570.0                  6.0                           5865   
3         982.0                 14.0                         543983   
4         145.0                  NaN                           2853   

   total_deaths_per_1m_population  total_tests  total_tests_per_1m_population  \
0                           190.0     951337.0                        23455.0   
1                          1218.0    1817530.0                       632857.0   
2                           152.0     230861.0                         5093.0   
3                          1974.0     249838.0                      3223924.0   
4                            55.0    1499795.0                        43136.0   

   population  
0    40560636  
1     2871945  
2    45325517  
3       77495  
4    34769277

In [27]:
covid_data.tail(8)

country          continent  total_confirmed  \
218                    Vanuatu  Australia/Oceania             8457   
219                  Venezuela      South America           522921   
220                   Viet Nam               Asia         10696630   
221  Wallis And Futuna Islands  Australia/Oceania              454   
222             Western Sahara             Africa               10   
223                      Yemen               Asia            11819   
224                     Zambia             Africa           320591   
225                   Zimbabwe             Africa           249206   

     total_deaths  total_recovered  active_cases  serious_or_critical  \
218          14.0           7974.0         469.0                  NaN   
219        5711.0         516170.0        1040.0                230.0   
220       43065.0        9355040.0     1298525.0                340.0   
221           7.0            438.0           9.0                  NaN   
222           1.0              9.0           0.0                  NaN   
223        2149.0           9009.0         661.0                 23.0   
224        3983.0         315997.0         611.0                  NaN   
225        5482.0         242417.0        1307.0                 12.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
218                          26386                            44.0   
219                          18487                           202.0   
220                         108080                           435.0   
221                          41755                           644.0   
222                             16                             2.0   
223                            381                            69.0   
224                          16575                           206.0   
225                          16324                           359.0   

     total_tests  total_tests_per_1m_population  population  
218      24976.0                        77926.0      320508  
219    3359014.0                       118752.0    28285909  
220   85811485.0                       867048.0    98969721  
221      20508.0                      1886140.0       10873  
222          NaN                            NaN      624681  
223     265253.0                         8543.0    31049015  
224    3452554.0                       178497.0    19342381  
225    2287793.0                       149863.0    15265849

In [28]:
nba_data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")

nba_data.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [29]:
nba_data.to_csv("./nba_data.csv")

#### shape

In [31]:
covid_data.shape

(226, 12)

In [32]:
len(covid_data)

226

In [33]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   country                         226 non-null    object 
 1   continent                       226 non-null    object 
 2   total_confirmed                 226 non-null    int64  
 3   total_deaths                    218 non-null    float64
 4   total_recovered                 204 non-null    float64
 5   active_cases                    204 non-null    float64
 6   serious_or_critical             145 non-null    float64
 7   total_cases_per_1m_population   226 non-null    int64  
 8   total_deaths_per_1m_population  218 non-null    float64
 9   total_tests                     212 non-null    float64
 10  total_tests_per_1m_population   212 non-null    float64
 11  population                      226 non-null    int64  
dtypes: float64(7), int64(3), object(2)
m

In [34]:
covid_data.describe()

total_confirmed  total_deaths  total_recovered  active_cases  \
count     2.260000e+02  2.180000e+02     2.040000e+02  2.040000e+02   
mean      2.305651e+06  2.884442e+04     2.256851e+06  6.861029e+04   
std       7.575510e+06  9.971254e+04     7.613357e+06  2.350430e+05   
min       2.000000e+00  1.000000e+00     1.000000e+00  0.000000e+00   
25%       2.412600e+04  2.370000e+02     1.619300e+04  2.397500e+02   
50%       1.793750e+05  2.251500e+03     1.372740e+05  1.634000e+03   
75%       1.090902e+06  1.400650e+04     1.006245e+06  1.929675e+04   
max       8.420947e+07  1.026646e+06     8.124426e+07  1.938567e+06   

       serious_or_critical  total_cases_per_1m_population  \
count           145.000000                     226.000000   
mean            269.482759                  148156.809735   
std             883.174727                  155202.909225   
min               1.000000                      16.000000   
25%               5.000000                   11748.250000   
50%              17.000000                   98271.500000   
75%             139.000000                  255632.750000   
max            8318.000000                  704302.000000   

       total_deaths_per_1m_population   total_tests  \
count                      218.000000  2.120000e+02   
mean                      1157.550459  2.987445e+07   
std                       1212.833590  1.079635e+08   
min                          2.000000  5.117000e+03   
25%                        172.500000  3.472968e+05   
50%                        768.000000  2.238918e+06   
75%                       1850.000000  1.233862e+07   
max                       6297.000000  1.016883e+09   

       total_tests_per_1m_population    population  
count                   2.120000e+02  2.260000e+02  
mean                    1.944650e+06  3.495521e+07  
std                     3.318400e+06  1.390338e+08  
min                     5.093000e+03  8.050000e+02  
25%                     1.667260e+05  5.605125e+05  
50%                     7.753355e+05  5.800570e+06  
75%                     2.267408e+06  2.187284e+07  
max                     2.184247e+07  1.439324e+09

In [37]:
df = pd.DataFrame({'apple': [2, 3, 4], 'orange':[1, 5, np.nan]})

df

apple  orange
0      2     1.0
1      3     5.0
2      4     NaN

In [38]:
df.describe()

apple    orange
count    3.0  2.000000
mean     3.0  3.000000
std      1.0  2.828427
min      2.0  1.000000
25%      2.5  2.000000
50%      3.0  3.000000
75%      3.5  4.000000
max      4.0  5.000000

#### Slicing and Dicing

In [39]:
covid_data

country          continent  total_confirmed  \
0                  Afghanistan               Asia           179267   
1                      Albania             Europe           275574   
2                      Algeria             Africa           265816   
3                      Andorra             Europe            42156   
4                       Angola             Africa            99194   
..                         ...                ...              ...   
221  Wallis And Futuna Islands  Australia/Oceania              454   
222             Western Sahara             Africa               10   
223                      Yemen               Asia            11819   
224                     Zambia             Africa           320591   
225                   Zimbabwe             Africa           249206   

     total_deaths  total_recovered  active_cases  serious_or_critical  \
0          7690.0         162202.0        9375.0               1124.0   
1          3497.0         271826.0         251.0                  2.0   
2          6875.0         178371.0       80570.0                  6.0   
3           153.0          41021.0         982.0                 14.0   
4          1900.0          97149.0         145.0                  NaN   
..            ...              ...           ...                  ...   
221           7.0            438.0           9.0                  NaN   
222           1.0              9.0           0.0                  NaN   
223        2149.0           9009.0         661.0                 23.0   
224        3983.0         315997.0         611.0                  NaN   
225        5482.0         242417.0        1307.0                 12.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
0                             4420                           190.0   
1                            95954                          1218.0   
2                             5865                           152.0   
3                           543983                          1974.0   
4                             2853                            55.0   
..                             ...                             ...   
221                          41755                           644.0   
222                             16                             2.0   
223                            381                            69.0   
224                          16575                           206.0   
225                          16324                           359.0   

     total_tests  total_tests_per_1m_population  population  
0       951337.0                        23455.0    40560636  
1      1817530.0                       632857.0     2871945  
2       230861.0                         5093.0    45325517  
3       249838.0                      3223924.0       77495  
4      1499795.0                        43136.0    34769277  
..           ...                            ...         ...  
221      20508.0                      1886140.0       10873  
222          NaN                            NaN      624681  
223     265253.0                         8543.0    31049015  
224    3452554.0                       178497.0    19342381  
225    2287793.0                       149863.0    15265849  

[226 rows x 12 columns]

In [40]:
covid_data['total_confirmed']

0      179267
1      275574
2      265816
3       42156
4       99194
        ...  
221       454
222        10
223     11819
224    320591
225    249206
Name: total_confirmed, Length: 226, dtype: int64

In [41]:
type(covid_data['total_confirmed'])

pandas.core.series.Series

In [ ]:
covid_data.total_confirmed

0      179267
1      275574
2      265816
3       42156
4       99194
        ...  
221       454
222        10
223     11819
224    320591
225    249206
Name: total_confirmed, Length: 226, dtype: int64

In [43]:
data_selected = covid_data[['total_confirmed', 'total_deaths', 'total_recovered']]

data_selected

total_confirmed  total_deaths  total_recovered
0             179267        7690.0         162202.0
1             275574        3497.0         271826.0
2             265816        6875.0         178371.0
3              42156         153.0          41021.0
4              99194        1900.0          97149.0
..               ...           ...              ...
221              454           7.0            438.0
222               10           1.0              9.0
223            11819        2149.0           9009.0
224           320591        3983.0         315997.0
225           249206        5482.0         242417.0

[226 rows x 3 columns]

In [45]:
covid_data

country          continent  total_confirmed  \
0                  Afghanistan               Asia           179267   
1                      Albania             Europe           275574   
2                      Algeria             Africa           265816   
3                      Andorra             Europe            42156   
4                       Angola             Africa            99194   
..                         ...                ...              ...   
221  Wallis And Futuna Islands  Australia/Oceania              454   
222             Western Sahara             Africa               10   
223                      Yemen               Asia            11819   
224                     Zambia             Africa           320591   
225                   Zimbabwe             Africa           249206   

     total_deaths  total_recovered  active_cases  serious_or_critical  \
0          7690.0         162202.0        9375.0               1124.0   
1          3497.0         271826.0         251.0                  2.0   
2          6875.0         178371.0       80570.0                  6.0   
3           153.0          41021.0         982.0                 14.0   
4          1900.0          97149.0         145.0                  NaN   
..            ...              ...           ...                  ...   
221           7.0            438.0           9.0                  NaN   
222           1.0              9.0           0.0                  NaN   
223        2149.0           9009.0         661.0                 23.0   
224        3983.0         315997.0         611.0                  NaN   
225        5482.0         242417.0        1307.0                 12.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
0                             4420                           190.0   
1                            95954                          1218.0   
2                             5865                           152.0   
3                           543983                          1974.0   
4                             2853                            55.0   
..                             ...                             ...   
221                          41755                           644.0   
222                             16                             2.0   
223                            381                            69.0   
224                          16575                           206.0   
225                          16324                           359.0   

     total_tests  total_tests_per_1m_population  population  
0       951337.0                        23455.0    40560636  
1      1817530.0                       632857.0     2871945  
2       230861.0                         5093.0    45325517  
3       249838.0                      3223924.0       77495  
4      1499795.0                        43136.0    34769277  
..           ...                            ...         ...  
221      20508.0                      1886140.0       10873  
222          NaN                            NaN      624681  
223     265253.0                         8543.0    31049015  
224    3452554.0                       178497.0    19342381  
225    2287793.0                       149863.0    15265849  

[226 rows x 12 columns]

#### `iloc` method

In [58]:
covid_data.iloc[1]

country                             Albania
continent                            Europe
total_confirmed                      275574
total_deaths                         3497.0
total_recovered                    271826.0
active_cases                          251.0
serious_or_critical                     2.0
total_cases_per_1m_population         95954
total_deaths_per_1m_population       1218.0
total_tests                       1817530.0
total_tests_per_1m_population      632857.0
population                          2871945
Name: 1, dtype: object

In [53]:
covid_data.iloc[0,0]

'Afghanistan'

In [56]:
covid_data

country          continent  total_confirmed  \
0                  Afghanistan               Asia           179267   
1                      Albania             Europe           275574   
2                      Algeria             Africa           265816   
3                      Andorra             Europe            42156   
4                       Angola             Africa            99194   
..                         ...                ...              ...   
221  Wallis And Futuna Islands  Australia/Oceania              454   
222             Western Sahara             Africa               10   
223                      Yemen               Asia            11819   
224                     Zambia             Africa           320591   
225                   Zimbabwe             Africa           249206   

     total_deaths  total_recovered  active_cases  serious_or_critical  \
0          7690.0         162202.0        9375.0               1124.0   
1          3497.0         271826.0         251.0                  2.0   
2          6875.0         178371.0       80570.0                  6.0   
3           153.0          41021.0         982.0                 14.0   
4          1900.0          97149.0         145.0                  NaN   
..            ...              ...           ...                  ...   
221           7.0            438.0           9.0                  NaN   
222           1.0              9.0           0.0                  NaN   
223        2149.0           9009.0         661.0                 23.0   
224        3983.0         315997.0         611.0                  NaN   
225        5482.0         242417.0        1307.0                 12.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
0                             4420                           190.0   
1                            95954                          1218.0   
2                             5865                           152.0   
3                           543983                          1974.0   
4                             2853                            55.0   
..                             ...                             ...   
221                          41755                           644.0   
222                             16                             2.0   
223                            381                            69.0   
224                          16575                           206.0   
225                          16324                           359.0   

     total_tests  total_tests_per_1m_population  population  
0       951337.0                        23455.0    40560636  
1      1817530.0                       632857.0     2871945  
2       230861.0                         5093.0    45325517  
3       249838.0                      3223924.0       77495  
4      1499795.0                        43136.0    34769277  
..           ...                            ...         ...  
221      20508.0                      1886140.0       10873  
222          NaN                            NaN      624681  
223     265253.0                         8543.0    31049015  
224    3452554.0                       178497.0    19342381  
225    2287793.0                       149863.0    15265849  

[226 rows x 12 columns]

In [57]:
covid_data.iloc[0:5, 3:6]

total_deaths  total_recovered  active_cases
0        7690.0         162202.0        9375.0
1        3497.0         271826.0         251.0
2        6875.0         178371.0       80570.0
3         153.0          41021.0         982.0
4        1900.0          97149.0         145.0

In [62]:
covid_data.iloc[4:100:10]

country          continent  total_confirmed  total_deaths  \
4                   Angola             Africa            99194        1900.0   
14                 Bahrain               Asia           576997        1479.0   
24  Bosnia And Herzegovina             Europe           377511       15778.0   
34                Cameroon             Africa           119780        1927.0   
44                   China               Asia           221804        5209.0   
54                  Cyprus               Asia           477711        1032.0   
64       Equatorial Guinea             Africa            15910         183.0   
74        French Polynesia  Australia/Oceania            72821         649.0   
84              Guadeloupe      North America           140130         854.0   
94                   India               Asia         43121599      524214.0   

    total_recovered  active_cases  serious_or_critical  \
4           97149.0         145.0                  NaN   
14         569758.0        5760.0                  4.0   
24              NaN           NaN                  NaN   
34         117791.0          62.0                 13.0   
44         210454.0        6141.0                383.0   
54         124370.0      352309.0                 60.0   
64          15701.0          26.0                  5.0   
74              NaN           NaN                  7.0   
84           2250.0      137026.0                 19.0   
94       42579693.0       17692.0                698.0   

    total_cases_per_1m_population  total_deaths_per_1m_population  \
4                            2853                            55.0   
14                         318491                           816.0   
24                         116414                          4866.0   
34                           4312                            69.0   
44                            154                             4.0   
54                         390374                           843.0   
64                          10687                           123.0   
74                         256473                          2286.0   
84                         350105                          2134.0   
94                          30686                           373.0   

    total_tests  total_tests_per_1m_population  population  
4     1499795.0                        43136.0    34769277  
14    9775981.0                      5396149.0     1811659  
24    1767199.0                       544957.0     3242823  
34    1751774.0                        63068.0    27776053  
44  160000000.0                       111163.0  1439323776  
54    9477138.0                      7744481.0     1223728  
64     317211.0                       213068.0     1488778  
74          NaN                            NaN      283932  
84     938039.0                      2343627.0      400251  
94  843836914.0                       600479.0  1405273033

In [64]:
covid_data.iloc[2:15:3, ::2]

country  total_confirmed  total_recovered  serious_or_critical  \
2    Algeria           265816         178371.0                  6.0   
5   Anguilla             2984           2916.0                  4.0   
8    Armenia           422896         412048.0                  NaN   
11   Austria          4212492        4135885.0                 58.0   
14   Bahrain           576997         569758.0                  4.0   

    total_deaths_per_1m_population  total_tests_per_1m_population  
2                            152.0                         5093.0  
5                            590.0                      3368870.0  
8                           2900.0                      1031834.0  
11                          2011.0                     20328801.0  
14                           816.0                      5396149.0

In [ ]:
covid_data.iloc[0:15:3, ::2]   # stop value is not included

country  total_confirmed  total_recovered  \
0           Afghanistan           179267         162202.0   
3               Andorra            42156          41021.0   
6   Antigua And Barbuda             7721           7511.0   
9                 Aruba            35693          35199.0   
12           Azerbaijan           792638         782869.0   

    serious_or_critical  total_deaths_per_1m_population  \
0                1124.0                           190.0   
3                  14.0                          1974.0   
6                   1.0                          1378.0   
9                   NaN                          1979.0   
12                  NaN                           942.0   

    total_tests_per_1m_population  
0                         23455.0  
3                       3223924.0  
6                        190076.0  
9                       1653053.0  
12                       663324.0

In [65]:
covid_data.columns

Index(['country', 'continent', 'total_confirmed', 'total_deaths',
       'total_recovered', 'active_cases', 'serious_or_critical',
       'total_cases_per_1m_population', 'total_deaths_per_1m_population',
       'total_tests', 'total_tests_per_1m_population', 'population'],
      dtype='object')

#### `.loc` method

In [68]:
covid_data_selected = covid_data.loc[0:10, ['country', 'total_confirmed', 'total_deaths']]  # stop value is included

covid_data_selected

country  total_confirmed  total_deaths
0           Afghanistan           179267        7690.0
1               Albania           275574        3497.0
2               Algeria           265816        6875.0
3               Andorra            42156         153.0
4                Angola            99194        1900.0
5              Anguilla             2984           9.0
6   Antigua And Barbuda             7721         137.0
7             Argentina          9101319      128729.0
8               Armenia           422896        8623.0
9                 Aruba            35693         213.0
10            Australia          6593795        7794.0

In [69]:
covid_data['total_confirmed'] > 500000

0      False
1      False
2      False
3      False
4      False
       ...  
221    False
222    False
223    False
224    False
225    False
Name: total_confirmed, Length: 226, dtype: bool

In [70]:
covid_data[covid_data['total_confirmed']>500000]

country          continent  total_confirmed  total_deaths  \
7               Argentina      South America          9101319      128729.0   
10              Australia  Australia/Oceania          6593795        7794.0   
11                Austria             Europe          4212492       18303.0   
12             Azerbaijan               Asia           792638        9709.0   
14                Bahrain               Asia           576997        1479.0   
..                    ...                ...              ...           ...   
214  United Arab Emirates               Asia           902484        2302.0   
215               Uruguay      South America           902540        7213.0   
216                   USA      North America         84209473     1026646.0   
219             Venezuela      South America           522921        5711.0   
220              Viet Nam               Asia         10696630       43065.0   

     total_recovered  active_cases  serious_or_critical  \
7          8895999.0       76591.0                372.0   
10         6199822.0      386179.0                129.0   
11         4135885.0       58304.0                 58.0   
12          782869.0          60.0                  NaN   
14          569758.0        5760.0                  4.0   
..               ...           ...                  ...   
214         886128.0       14054.0                  NaN   
215         892434.0        2893.0                 18.0   
216       81244260.0     1938567.0               1941.0   
219         516170.0        1040.0                230.0   
220        9355040.0     1298525.0                340.0   

     total_cases_per_1m_population  total_deaths_per_1m_population  \
7                           197992                          2800.0   
10                          253112                           299.0   
11                          462804                          2011.0   
12                           76885                           942.0   
14                          318491                           816.0   
..                             ...                             ...   
214                          89240                           228.0   
215                         258152                          2063.0   
216                         251659                          3068.0   
219                          18487                           202.0   
220                         108080                           435.0   

      total_tests  total_tests_per_1m_population  population  
7    3.571607e+07                       776974.0    45968174  
10   7.088560e+07                      2721042.0    26050899  
11   1.850349e+08                     20328801.0     9102106  
12   6.838458e+06                       663324.0    10309383  
14   9.775981e+06                      5396149.0     1811659  
..            ...                            ...         ...  
214  1.591033e+08                     15732628.0    10112950  
215  6.114822e+06                      1749015.0     3496151  
216  1.016883e+09                      3038939.0   334617623  
219  3.359014e+06                       118752.0    28285909  
220  8.581148e+07                       867048.0    98969721  

[87 rows x 12 columns]

In [75]:
covid_data[(covid_data['total_confirmed']>500000) & (covid_data['total_deaths']>200000)]

country      continent  total_confirmed  total_deaths  total_recovered  \
26   Brazil  South America         30682094      664920.0       29718402.0   
94    India           Asia         43121599      524214.0       42579693.0   
131  Mexico  North America          5745652      324465.0        5044893.0   
158    Peru  South America          3571919      213023.0              NaN   
165  Russia         Europe         18260293      377670.0       17647179.0   
216     USA  North America         84209473     1026646.0       81244260.0   

     active_cases  serious_or_critical  total_cases_per_1m_population  \
26       298772.0               8318.0                         142460   
94        17692.0                698.0                          30686   
131      376294.0               4798.0                          43708   
158           NaN                248.0                         105593   
165      235444.0               2300.0                         125027   
216     1938567.0               1941.0                         251659   

     total_deaths_per_1m_population   total_tests  \
26                           3087.0  6.377617e+07   
94                            373.0  8.438369e+08   
131                          2468.0  1.585549e+07   
158                          6297.0  3.022687e+07   
165                          2586.0  2.734000e+08   
216                          3068.0  1.016883e+09   

     total_tests_per_1m_population  population  
26                        296119.0   215373503  
94                        600479.0  1405273033  
131                       120615.0   131455607  
158                       893567.0    33827210  
165                      1871949.0   146050996  
216                      3038939.0   334617623

In [76]:
covid_data_europe = covid_data[covid_data['continent']=='Europe']

In [77]:
covid_data_europe

country continent  total_confirmed  total_deaths  \
1                   Albania    Europe           275574        3497.0   
3                   Andorra    Europe            42156         153.0   
11                  Austria    Europe          4212492       18303.0   
17                  Belarus    Europe           982867        6978.0   
18                  Belgium    Europe          4116397       31613.0   
24   Bosnia And Herzegovina    Europe           377511       15778.0   
29                 Bulgaria    Europe          1161504       37045.0   
40          Channel Islands    Europe            75275         173.0   
51                  Croatia    Europe          1131450       15930.0   
55           Czech Republic    Europe          3915847       40245.0   
57                  Denmark    Europe          2976667        6287.0   
66                  Estonia    Europe           573922        2556.0   
68           Faeroe Islands    Europe            34658          28.0   
71                  Finland    Europe          1069740        4284.0   
72                   France    Europe         29160802      147257.0   
78                  Germany    Europe         25780226      137919.0   
80                Gibraltar    Europe            18129         102.0   
81                   Greece    Europe          3392575       29547.0   
90                 Holy See    Europe               29           NaN   
92                  Hungary    Europe          1909948       46343.0   
93                  Iceland    Europe           186545         120.0   
98                  Ireland    Europe          1535451        7203.0   
99              Isle Of Man    Europe            28416         105.0   
101                   Italy    Europe         17057873      165244.0   
111                  Latvia    Europe           825699        5798.0   
116           Liechtenstein    Europe            17347          84.0   
117               Lithuania    Europe          1060619        9127.0   
118              Luxembourg    Europe           244182        1073.0   
119               Macedonia    Europe           310684        9289.0   
125                   Malta    Europe            93508         713.0   
133                 Moldova    Europe           516986       11489.0   
134                  Monaco    Europe            12004          54.0   
136              Montenegro    Europe           236277        2719.0   
144             Netherlands    Europe          8067116       22292.0   
151                  Norway    Europe          1429717        3061.0   
160                  Poland    Europe          6003436      116207.0   
161                Portugal    Europe          4066674       22583.0   
164                 Romania    Europe          2903072       65612.0   
165                  Russia    Europe         18260293      377670.0   
175              San Marino    Europe            16852         115.0   
179                  Serbia    Europe          2012836       16049.0   
184                Slovakia    Europe          1787093       20041.0   
185                Slovenia    Europe          1019468        6622.0   
191                   Spain    Europe         12127122      105444.0   
197                  Sweden    Europe          2504894       18864.0   
198             Switzerland    Europe          3631881       13882.0   
212                      UK    Europe         22159805      176708.0   
213                 Ukraine    Europe          5006460      108449.0   

     total_recovered  active_cases  serious_or_critical  \
1           271826.0         251.0                  2.0   
3            41021.0         982.0                 14.0   
11         4135885.0       58304.0                 58.0   
17               NaN           NaN                  NaN   
18         3941350.0      143434.0                117.0   
24               NaN           NaN                  NaN   
29         1014302.0      110157.0                 54.0   
40           74574.

In [79]:
covid_data_europe.to_numpy().shape

(48, 12)

In [80]:
covid_data_europe['total_confirmed'].values

array([  275574,    42156,  4212492,   982867,  4116397,   377511,
        1161504,    75275,  1131450,  3915847,  2976667,   573922,
          34658,  1069740, 29160802, 25780226,    18129,  3392575,
             29,  1909948,   186545,  1535451,    28416, 17057873,
         825699,    17347,  1060619,   244182,   310684,    93508,
         516986,    12004,   236277,  8067116,  1429717,  6003436,
        4066674,  2903072, 18260293,    16852,  2012836,  1787093,
        1019468, 12127122,  2504894,  3631881, 22159805,  5006460])