## Linear Algebra with numpy

In [2]:
import numpy as np

In [3]:
A = np.matrix([[5, 6, 2],
               [4, 7, 9],
               [0, 3, 12]])

In [7]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [5]:
type(A)

numpy.matrix

In [6]:
B = np.array([[14, -2, 12], [4, 4, 5], [5, 2, 1]])

B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [8]:
type(B)

numpy.ndarray

### Identity matrix

In [21]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)  # np.eye() is an alias to np.identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Transpose

In [9]:
B.T

array([[14,  4,  5],
       [-2,  4,  2],
       [12,  5,  1]])

In [10]:
A.T

matrix([[ 5,  4,  0],
        [ 6,  7,  3],
        [ 2,  9, 12]])

### Addition

In [11]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 14],
        [ 5,  5, 13]])

In [12]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,   4],
        [ -5,   1,  11]])

### Scalar multiplication

In [14]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [13]:
k = 3.5

k * A

matrix([[17.5, 21. ,  7. ],
        [14. , 24.5, 31.5],
        [ 0. , 10.5, 42. ]])

In [16]:
B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [ ]:
B/k  # if k != 0

array([[ 4.        , -0.57142857,  3.42857143],
       [ 1.14285714,  1.14285714,  1.42857143],
       [ 1.42857143,  0.57142857,  0.28571429]])

### Element wise multiplication (Hadamard product)

In [ ]:
np.multiply(A, B)   # element-wise multiplication

matrix([[ 70, -12,  24],
        [ 16,  28,  45],
        [  0,   6,  12]])

In [18]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [19]:
B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [ ]:
A * B   # this is not element-wise multiplication

matrix([[104,  18,  92],
        [129,  38,  92],
        [ 72,  36,  27]])

### Vector - Matrix multiplication

#### Post - multiplication 

In [24]:
v = np.array([1, 2, 3])

v.shape

(3,)

In [27]:
M = np.matrix([[5, -1], [6, 2], [7, 3]])

In [29]:
C = v * M

In [30]:
C.shape

(1, 2)

In [33]:
type(C)

numpy.matrix

In [31]:
np.dot(v, M)

matrix([[38, 12]])

In [32]:
v @ M

matrix([[38, 12]])

### Pre-multiplication

In [34]:
M = np.matrix([[2, 3, 0, -1],[6, 7, -2, 1]])

M.shape

(2, 4)

In [35]:
v = np.array([0.5, 1, -1, 0])

In [38]:
np.dot(M, v)

matrix([[ 4., 12.]])

In [39]:
M @ v

matrix([[ 4., 12.]])

In [43]:
w = np.array([1, 2, 3, 4])

np.dot(v, w)

np.float64(-0.5)

### Determinant value of a square matrix

In [45]:
mat = np.matrix([[2, 4, 5], [3, 2, 1], [1, 5, -2]])

print(mat)

[[ 2  4  5]
 [ 3  2  1]
 [ 1  5 -2]]


In [46]:
np.linalg.det(mat)

np.float64(74.99999999999997)

### Eigen values and Eigen vectors

In [47]:
A = np.matrix([[4, -1],[2, 1]])

In [48]:
np.linalg.det(A)

np.float64(6.0)

In [49]:
np.linalg.eig(A)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=matrix([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]]))

In [50]:
v, B = np.linalg.eig(A)

In [51]:
v

array([3., 2.])

In [52]:
B

matrix([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]])

In [55]:
v, B = np.linalg.eig(mat)

In [59]:
print(v)

[ 7.12577876+0.j         -2.56288938+1.98916149j -2.56288938-1.98916149j]


In [58]:
print(B)

[[ 0.76844087+0.j         -0.70202669+0.j         -0.70202669-0.j        ]
 [ 0.52197261+0.j          0.27371705+0.2189159j   0.27371705-0.2189159j ]
 [ 0.37019349+0.j          0.42168038-0.45442161j  0.42168038+0.45442161j]]


### Matix - Matrix multiplication

In [60]:
A = np.matrix([[2, 3, 4, 5], [6, 7, 8, 9], [1, -1, 2, 3]])

B = np.matrix([[1, 3], [-1, 0], [0, -2], [2, 1]])

In [61]:
np.dot(A, B)

matrix([[ 9,  3],
        [17, 11],
        [ 8,  2]])

In [62]:
np.dot(B, A)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

### [Cayley-Hamilton's theorem](https://en.wikipedia.org/wiki/Cayley%E2%80%93Hamilton_theorem#:~:text=In%20linear%20algebra%2C%20the%20Cayley,satisfies%20its%20own%20characteristic%20equation.)

In [63]:
A = np.matrix([[4, -1],[2, 1]])

In [64]:
np.dot(A,A) - np.multiply(5, A) + np.multiply(6, np.eye(2))

matrix([[0., 0.],
        [0., 0.]])

### Inverse of a matrix

In [65]:
A

matrix([[ 4, -1],
        [ 2,  1]])

In [66]:
np.linalg.det(A)

np.float64(6.0)

In [67]:
B = np.linalg.inv(A)

In [68]:
B

matrix([[ 0.16666667,  0.16666667],
        [-0.33333333,  0.66666667]])

In [69]:
np.dot(A, B)

matrix([[1.00000000e+00, 0.00000000e+00],
        [5.55111512e-17, 1.00000000e+00]])

In [71]:
np.round(np.dot(B, A), 2)

array([[ 1., -0.],
       [ 0.,  1.]])

In [72]:
np.linalg.det(B)

np.float64(0.16666666666666669)