### Importing libraries

Library in python is a collection of classes and corresponding methods.

In [3]:
from operations import Person, Employee

In [4]:
p1 = Person("Amit", 29, "Indian", ['music', 'guitar'])

In [5]:
p1.show_skills()

Skills are: ['music', 'guitar']


In [6]:
p1

In [1]:
from operations import do_some_operation

In [2]:
do_some_operation(4)

22

In [4]:
do_some_operation(5)

32

In [6]:
from operations import *    # imports everything from the package (library)

In [ ]:
Person

In [1]:
import operations # Referring to the library. To refer any class or functions within the library you need to call it by <package_name>.<class_name>

p = operations.Person("Ria", 28, "Indian", ["singing", "dancing"])

In [2]:
p

In [7]:
# Aliasing the package

import operations as ops  # ops is the alias to the package operations

In [8]:
ops.do_some_operation(10)

112

In [9]:
import math

In [10]:
math.pi

3.141592653589793

In [11]:
math.sqrt(196)

14.0

In [12]:
math.isqrt(400)

20

In [13]:
math.pow(3,4)

81.0

In [14]:
math.log(100)  # natural logarithm

4.605170185988092

In [15]:
math.exp(7)  # e^7

1096.6331584284585

[Documentation of math module (package / library)](https://docs.python.org/3/library/math.html)

In [16]:
import string

In [17]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [18]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [19]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [20]:
string.digits

'0123456789'

In [21]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
s = "this is a great c@ountry. we live #here since I$ was young. I live with my wife, and two dogs."

In [26]:
punc_count = 0

for i in range(len(s)):
    if s[i] in string.punctuation:
        punc_count += 1

In [27]:
punc_count

7

[Documentation of String module.](https://docs.python.org/3/library/string.html)

## NumPy

- NumPy is a python library that provides a simple yet powerful data structure: **n-dimesnional array**
- This is the foundaton on which almost all of the power of Python's data science toolkit is built.
- The official documentation of numpy: [numpy.org](https://numpy.org/)

In [1]:
# import numpy

import numpy as np

### Creating numpy array from list

In [2]:
list_1 = [2, 4, 3, 6, 8, 7]

x = np.array(list_1)

In [4]:
print(type(list_1))

<class 'list'>


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
x

array([2, 4, 3, 6, 8, 7])

In [26]:
list_2 = [[1, 2, 3], [4, 5, 6]]  # 2D list (list of lists)

In [27]:
y = np.array(list_2) # 2D array

In [9]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(type(y))

<class 'numpy.ndarray'>


In [15]:
list_3d = [[[1, 2, 3], [4, 5, 6]], [[-1, 2, -3], [4, -5, 6]], [[2, 4, 5], [3, 4, 5]]] # 3D list (list of lists of lists)

list_3d

[[[1, 2, 3], [4, 5, 6]], [[-1, 2, -3], [4, -5, 6]], [[2, 4, 5], [3, 4, 5]]]

In [17]:
z = np.array(list_3d)  # 3D array

print(type(z)) 

<class 'numpy.ndarray'>


In [18]:
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[-1,  2, -3],
        [ 4, -5,  6]],

       [[ 2,  4,  5],
        [ 3,  4,  5]]])

In [20]:
x.shape  # return a tuple containing the shape of the array

(6,)

In [21]:
y.shape

(2, 3)

In [22]:
z.shape

(3, 2, 3)

### Create NumPy array from linearly spaced data

We will use `numpy.linspace` function for it

In [28]:
a = np.linspace(start=0, stop=100, num=21)   # both start and stop are included

a

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [29]:
b = np.linspace(start=20, stop=500, num=30)   # both start and stop are included

b

array([ 20.        ,  36.55172414,  53.10344828,  69.65517241,
        86.20689655, 102.75862069, 119.31034483, 135.86206897,
       152.4137931 , 168.96551724, 185.51724138, 202.06896552,
       218.62068966, 235.17241379, 251.72413793, 268.27586207,
       284.82758621, 301.37931034, 317.93103448, 334.48275862,
       351.03448276, 367.5862069 , 384.13793103, 400.68965517,
       417.24137931, 433.79310345, 450.34482759, 466.89655172,
       483.44827586, 500.        ])

In [61]:
b = np.linspace(start=200, stop=-100, num=50)

b

array([ 200.        ,  193.87755102,  187.75510204,  181.63265306,
        175.51020408,  169.3877551 ,  163.26530612,  157.14285714,
        151.02040816,  144.89795918,  138.7755102 ,  132.65306122,
        126.53061224,  120.40816327,  114.28571429,  108.16326531,
        102.04081633,   95.91836735,   89.79591837,   83.67346939,
         77.55102041,   71.42857143,   65.30612245,   59.18367347,
         53.06122449,   46.93877551,   40.81632653,   34.69387755,
         28.57142857,   22.44897959,   16.32653061,   10.20408163,
          4.08163265,   -2.04081633,   -8.16326531,  -14.28571429,
        -20.40816327,  -26.53061224,  -32.65306122,  -38.7755102 ,
        -44.89795918,  -51.02040816,  -57.14285714,  -63.26530612,
        -69.3877551 ,  -75.51020408,  -81.63265306,  -87.75510204,
        -93.87755102, -100.        ])

### NumPy data type

`numpy.ndarray` is the fundamental data type of numpy.

ndarray is different from python's native list in the following way.

- ndarray only accepts homogenous data type
- The data within the ndarray must be on the dtypes provided by numpy

few popular dtypes are:

- float64
- int64
- int32
- bool
- datetime
and many more

In [30]:
x

array([2, 4, 3, 6, 8, 7])

In [31]:
type(x[0])

numpy.int64

In [33]:
z = np.array([1,2,3], dtype='int32')

In [34]:
type(z[0])

numpy.int32

In [37]:
y = np.array([3,4,7], dtype='float32')

y

array([3., 4., 7.], dtype=float32)

In [38]:
type(y[0])

numpy.float32

In [39]:
c = np.array([0, 1, 1, 0, 0], dtype='bool')

In [40]:
c

array([False,  True,  True, False, False])

In [41]:
type(c[0])

numpy.bool

In [46]:
d = np.array([5, -1, 1, 0, 0], dtype='bool')

In [47]:
d

array([ True,  True,  True, False, False])

### Creating arrays with all the zero values

In [54]:
np.zeros((4,), dtype='int') # array initialized with zero

array([0, 0, 0, 0])

In [49]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [51]:
np.empty((5,)) # uninitialized

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.14243327e-311,
       0.00000000e+000])

In [55]:
v = np.array([[1,2,3], [4,5,6], [7,8,9]])

v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
v.shape

(3, 3)

In [57]:
u = np.zeros_like(v)

u

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Creating arrays with all ones

In [52]:
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones_like(v)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Identity matrix

In [59]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
np.eye(5)  # alias to the function np.identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### numpy.arrange

In [63]:
np.arange(start=0, stop=10, step=3)  # stop is excluded, start is included. 

array([0, 3, 6, 9])

## Shape and axis

In [64]:
x2d = np.array([[2, 3, 4], [9, 8, 7]])

In [65]:
x2d

array([[2, 3, 4],
       [9, 8, 7]])

In [66]:
x2d.shape

(2, 3)

In [69]:
x2d.reshape((3,2))

array([[2, 3],
       [4, 9],
       [8, 7]])

In [70]:
v = np.linspace(0, 100, 21)

v

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [71]:
v.shape

(21,)

In [72]:
v.reshape((3,7))

array([[  0.,   5.,  10.,  15.,  20.,  25.,  30.],
       [ 35.,  40.,  45.,  50.,  55.,  60.,  65.],
       [ 70.,  75.,  80.,  85.,  90.,  95., 100.]])

In [73]:
x2d

array([[2, 3, 4],
       [9, 8, 7]])

In [74]:
x2d.flatten()

array([2, 3, 4, 9, 8, 7])

In [78]:
x2d = np.array([[3.5, 6.4, 2.7], [5.9, 6.1, 7.3]])

In [79]:
np.sum(x2d) # sum of all the elements

np.float64(31.900000000000002)

In [80]:
x2d

array([[3.5, 6.4, 2.7],
       [5.9, 6.1, 7.3]])

In [93]:
x2d.shape

(2, 3)

In [81]:
np.sum(x2d, axis=0) # column wise sum

array([ 9.4, 12.5, 10. ])

In [82]:
np.sum(x2d, axis=1) # row wise sum

array([12.6, 19.3])

In [89]:
x = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[5, 7, 9, 11], [2, 4, 6, 8]], [[-1, -2, 4, 9], [2, -7, 5, 0]]])

In [90]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 5,  7,  9, 11],
        [ 2,  4,  6,  8]],

       [[-1, -2,  4,  9],
        [ 2, -7,  5,  0]]])

In [91]:
x.shape

(3, 2, 4)

In [92]:
np.sum(x, axis=0)  # result dimension is (2,4)

array([[ 5,  7, 16, 24],
       [ 9,  3, 18, 16]])

In [94]:
np.sum(x, axis=1) # result dimension is (3,4)

array([[ 6,  8, 10, 12],
       [ 7, 11, 15, 19],
       [ 1, -9,  9,  9]])

In [95]:
np.sum(x, axis=2) # result dimension is (3,2)

array([[10, 26],
       [32, 20],
       [10,  0]])

### Indexing and Slicing

In [100]:
y = np.array([1,2,3,4,5])

y[0]

np.int64(1)

In [101]:
y[4]

np.int64(5)

In [102]:
y[-1]

np.int64(5)

In [103]:
y[2:4]

array([3, 4])

In [104]:
y[:3]

array([1, 2, 3])

In [105]:
y[2:]

array([3, 4, 5])

In [98]:
z = np.linspace(1,24,24).reshape(4,6)  # 2D array of shape (4,6)

In [99]:
z

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.]])

In [106]:
z[0]

array([1., 2., 3., 4., 5., 6.])

In [110]:
z[0,4]

np.float64(5.0)

In [111]:
z[1,3]

np.float64(10.0)

In [112]:
z[1,:]  

array([ 7.,  8.,  9., 10., 11., 12.])

In [113]:
z[:,3]

array([ 4., 10., 16., 22.])

In [114]:
z[1:3, 2:5]

array([[ 9., 10., 11.],
       [15., 16., 17.]])

In [115]:
z

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.]])

In [116]:
z[1:4, 1:6:2]

array([[ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 24.]])

### Boolean indexing

In [117]:
v = np.array([-1,4,2,7,10,9,3,5])

In [118]:
v.shape

(8,)

In [125]:
bool_index = np.array([1, 1, 0, 0, 0, 1, 0, 0], dtype='bool')

In [126]:
bool_index

array([ True,  True, False, False, False,  True, False, False])

In [128]:
v[bool_index]

array([-1,  4,  9])

In [127]:
v[~bool_index]

array([ 2,  7, 10,  3,  5])

In [129]:
v > 2

array([False,  True, False,  True,  True,  True,  True,  True])

In [130]:
v[v > 2]

array([ 4,  7, 10,  9,  3,  5])

In [131]:
(v > 2) & (v < 9)   # & -> and operation

array([False,  True, False,  True, False, False,  True,  True])

In [132]:
v[(v > 2) & (v < 9)]

array([4, 7, 3, 5])

In [134]:
(v < 5) | (v == 10) # | -> or operation

array([ True,  True,  True, False,  True, False,  True, False])

In [135]:
v[(v < 5) | (v == 10)]

array([-1,  4,  2, 10,  3])

### Array methods

In [136]:
x = np.array([3, -1, 4, 8, 0, 2])

In [137]:
x.sort()  # in-place sorting 

In [138]:
x

array([-1,  0,  2,  3,  4,  8])

In [143]:
x.sort()
x = x[::-1]

x

array([ 8,  4,  3,  2,  0, -1])

In [145]:
y = np.array([3, -1, 4, 8, 0, 2])

y.argsort()

array([1, 4, 5, 0, 2, 3])

In [146]:
y.argsort()[-1]

np.int64(3)

In [149]:
y.min()

np.int64(-1)

In [150]:
y.argmin()

np.int64(1)

In [151]:
y.max()

np.int64(8)

In [152]:
y.argmax()

np.int64(3)

In [153]:
x = np.array([1, 2, -1, 4, 0, 5, 7, 8])

In [154]:
np.cumsum(x)  # cumulative summation

array([ 1,  3,  2,  6,  6, 11, 18, 26])

In [155]:
z = np.cumprod(x)

In [156]:
z

array([ 1,  2, -2, -8,  0,  0,  0,  0])

### mutability and copy of numpy array

In [160]:
a = [1, 3, 4]

b = a  # pointing to the same memory location

In [158]:
b.append(5)

b

[1, 3, 4, 5]

In [159]:
a

[1, 3, 4, 5]

In [161]:
a[0] = 56

In [162]:
b

[56, 3, 4]

In [163]:
a

[56, 3, 4]

In [165]:
b = a.copy()  # copies the same elements to a different memory location

In [167]:
b.append(16)

In [168]:
b

[56, 3, 4, 16]

In [169]:
a

[56, 3, 4]

In [178]:
x = np.array((4, 5, 6, 10))

In [179]:
y = x.copy()

In [180]:
x[2] = 23

In [181]:
x

array([ 4,  5, 23, 10])

In [182]:
y

array([ 4,  5,  6, 10])